[project]
name = "lexigram"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "aws-cdk-lib>=2.184.1",
    "aws-lambda-powertools>=3.8.0",
    "aws-lambda-typing>=2.20.0",
    "beautifulsoup4>=4.13.3",
    "boto3>=1.37.15",
    "constructs>=10.4.2",
    "crewai>=0.108.0",
    "dotenv>=0.9.9",
    "openai>=1.66.5",
    "pydantic>=2.10.6",
    "requests>=2.32.3",
]

[tool.pytest.ini_options]
pythonpath = "."

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "pytest-mock>=3.14.0",
    "ruff>=0.9.6",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.9",
]

[tool.ruff]
line-length = 88
lint.extend-select = ["I", "W292"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
