[project]
name = "lexigram"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aws-cdk-lib>=2.179.0",
    "aws-lambda-powertools>=3.6.0",
    "aws-lambda-typing>=2.20.0",
    "aws-xray-sdk>=2.14.0",
    "constructs>=10.4.2",
    "crewai>=0.102.0",
    "crewai-tools>=0.36.0",
    "dotenv>=0.9.9",
    "pydantic>=2.10.6",
    "requests>=2.32.3",
]

[tool.pytest.ini_options]
pythonpath = "."

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "pytest-mock>=3.14.0",
    "ruff>=0.9.6",
]

[tool.ruff]
line-length = 88
lint.extend-select = ["I", "W292"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"