name: Deploy to AWS using CDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: python:3.12
      options: --privileged -v /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Check Docker Access
        run: docker version

      - name: Setup Common Environment
        uses: ./.github/actions/setup
        with:
          install-all-extras: 'false'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          env-content: ${{ secrets.ENV }}

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Deploy CDK Stack
        run: uv run cdk deploy --all --require-approval=never
        env:
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: eu-west-3
