name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    container:
      image: python:3.12

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Common Environment
        uses: ./.github/actions/setup
        with:
          install-all-extras: 'true'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          env-content: ${{ secrets.ENV }}

      - name: Run tests with coverage
        run: uv run ./scripts/generate_coverage_report.py

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
